name = "browser-worker"
main = "src/index.js"
compatibility_date = "2025-12-28"
compatibility_flags = [ "nodejs_compat" ]

browser = { binding = "MYBROWSER" }
kv_namespaces = [
  { binding = "BROWSER_KV_DEMO", id = "f5b9998e03fb41bc9a6d0d6da97c86a3" }
]